// Copyright (c) SharpCrafters s.r.o. See the LICENSE.md file in the root directory of this repository root for details.

using JetBrains.Annotations;

namespace Metalama.Patterns.Contracts;

/// <summary>
/// A disposable cookie returned by the <c>SuspendInvariants</c> method generated by the <see cref="InvariantAttribute"/> aspect.
/// </summary>
[PublicAPI]
public struct SuspendInvariantsCookie : IDisposable
{
    private readonly InvariantSuspensionCounter _counter;
    private bool _disposed;

    public SuspendInvariantsCookie( InvariantSuspensionCounter counter )
    {
        this._counter = counter;
    }

    public void Dispose()
    {
        if ( !this._disposed )
        {
            this._counter.Decrement();
            this._disposed = true;
        }
    }
}