// Error LAMA5207 on `Foo`: `No match was found using the rx1-name, rx2-name and rx3-name naming conventions. See other warnings for details.`
// Warning LAMA5206 on `Foo`: `No property-changed method was found using the rx2-name naming convention, with candidate member name 'OnFooChanged'.`
// Warning LAMA5206 on `Foo`: `No property-changed method was found using the rx3-name naming convention, with candidate member name 'OnFooChanged'.`
// Warning LAMA5206 on `Foo`: `No property-changing method was found as required by the rx3-name naming convention, with candidate member name 'FooRx3Ing'.`
// Warning LAMA5206 on `Foo`: `No validate method was found using the rx1-name naming convention, with candidate member name 'ValidateFoo'.`
// Warning LAMA5206 on `Foo`: `No validate method was found using the rx2-name naming convention, with candidate member name 'ValidateFoo'.`
// Warning LAMA5206 on `Foo`: `No validate method was found using the rx3-name naming convention, with candidate member name 'ValidateFoo'.`
// Warning LAMA5205 on `FooRx1Ing`: `The method was identified as a valid candidate property-changing method for [DependencyProperty] property MultipleNamingConventionsNoMatch.Foo as required by the rx1-name naming convention, but other members also matched.`
// Warning LAMA5205 on `FooRx1Ing`: `The method was identified as a valid candidate property-changing method for [DependencyProperty] property MultipleNamingConventionsNoMatch.Foo as required by the rx1-name naming convention, but other members also matched.`
// Warning LAMA5204 on `FooRx2Ing`: `The method was identified as a candidate property-changing method for [DependencyProperty] property MultipleNamingConventionsNoMatch.Foo as required by the rx2-name naming convention, but the signature is not valid. Refer to documentation for supported method signatures.`